### ISSUE TITLE
mutect pipeline failed in "gatk_realign_info" step

### ISSUE THREAD

**Issue by wiseflying** [gis-rpd/pipelines#85]
Dear RPD, 

First time running the mutect pipeline for WES data and got the following error. Tried "qsub run.sh ..." too but didn't help.

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error in job gatk_realign_info while creating output files ./out/normal/normal.bwamem.dedup.realn.intervals, ./out/tumor/tumor.bwamem.dedup.realn.intervals.
[Tue Nov 22 15:35:57 2016] ClusterJobException in line 28 of /mnt/projects/rpd/pipelines/pipelines.2016-10/somatic/mutect/gatk_mapping.rules:
Error executing rule gatk_realign_info on cluster (jobid: 10, jobscript: /mnt/projects/lihp/singlecelljco/Elise_new_data/CRC_exome_seq_data/DATA_for_RPD_20161121somatic_analysis/somatic_out/CRC858/.snakemake/tmp.FIYDZA/mutect.slave.gatk_realign_info.10.sh). For detailed error see the **cluster log**.
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Is the "cluster log" accessible somewhere? 

Thanks! 

lihp

**Comment by andreas-wilm** [comment]
Hi Hui Peng,

yes the cluster logs are in the corresponding logs folder.

You can find a writeup on troubleshooting here: http://wiki.gis.a-star.edu.sg/index.php/RpdFramework2016TroubleshootingHowto

In general: first check the logs/snakemake.log file. In your case it indicates that the job gatk_realign_info failed. From there you can also see that the log file for that command was ./out/normal/normal.bwamem.dedup.realn.intervals.log. And in there you see the following GATK error message:

`ERROR MESSAGE: File associated with name /home/lihp/ROI_files/SeqCapEZ_Exome_v3.0_Design_Annotation_files/SeqCap_EZ_Exome_v3_hg19_primary_targets.bed is malformed: Problem reading the interval file caused by Badly formed genome loc: Contig chr1 given as location, but this contig isn't present in the Fasta sequence dictionary`

I don't have permissions to read that file, but I guess it's the typical problem of present 'chr' prefixes. Just remove and rerun.

Andreas

**Comment by wiseflying** [comment]
Thanks for the quick reply, Andreas!

It is now working after removing "chr". 

best
Huipeng

**Comment by wiseflying** [comment]
Hi, Andreas

The mutect pipeline runs smoothly till the recalibration is done. But encountered an error at the mutect variant calling step. 

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[Wed Noev 23 09:57:55 2016] ClusterJobException in line 126 of /mnt/projects/rpd/pipelines/pipelines.2016-10/somatic/mutect/Snakefile:
Error executing rule mutect_per_region on cluster (jobid: 17, jobscript: /mnt/projects/lihp/singlecelljco/Elise_new_data/CRC_exome_seq_data/DATA_for_RPD_20161121somatic_analysis/somatic_out/CRC1127/.snakemake/tmp.E1SX5U/mutect.slave.mutect_per_region.17.sh). For detailed error see the cluster log.
[Wed Nov 23 09:57:55 2016] Will exit after finishing currently running jobs.
[Wed Nov 23 09:58:51 2016] Error in job mutect_per_region while creating output files ./out/variants/mutect.0.wig, ./out/variants/mutect.0.vcf, ./out/variants/mutect.0.vcf.idx, ./out/variants/mutect.0.txt.
[Wed Nov 23 09:58:51 2016] ClusterJobException in line 126 of /mnt/projects/rpd/pipelines/pipelines.2016-10/somatic/mutect/Snakefile:
Error executing rule mutect_per_region on cluster (jobid: 15, jobscript: /mnt/projects/lihp/singlecelljco/Elise_new_data/CRC_exome_seq_data/DATA_for_RPD_20161121somatic_analysis/somatic_out/CRC1127/.snakemake/tmp.E1SX5U/mutect.slave.mutect_per_region.15.sh). For detailed error see the cluster log.
[Wed Nov 23 09:58:51 2016] Will exit after finishing currently running jobs.
[Wed Nov 23 09:58:52 2016] Exiting because a job execution failed. Look above for error message
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

No obvious error was found in the output folder log files. 

best
Huipeng

**Comment by andreas-wilm** [comment]
From qacct you can see that these jobs were killed by the cluster. The reason is the recent cluster upgrade, which changed the way memory use is accounted. Now some jobs apparently go over the memory limit (this will yet again change next week with the RSS changes John announced). This is annoying for all of us. Sorry for the inconvenience caused.

I've changed the default memory limits for mutect in the pipeline scripts just now. New calls of the pipeline script should just work.

For the existing run that you have, I would suggest to update the (locally defined) cluster limits and rerun from where it stopped, which can be achieved as follows:

```
cd /mnt/projects/lihp/singlecelljco/Elise_new_data/CRC_exome_seq_data/DATA_for_RPD_20161121somatic_analysis/somatic_out/CRC1127;
sed -i -e 's,8G,12G,' cluster.yaml;
qsub run.sh >> logs/submission.log;
```

**Comment by wiseflying** [comment]
Thanks, Anreas! It's working now. 

Huipeng
